# Generated by Django 5.2.1 on 2025-05-25 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
